repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-json

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--line-length=100]
        additional_dependencies: []

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        additional_dependencies: []

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [
          "--ignore-words-list=teh,ot,fo",
          "--skip=*.ipynb,*.svg,*.pdf,*.png,*.jpg,*.gif,*.mp4,*.mov,docs/export/*",
        ]

ci:
  autofix_prs: true
  autofix_commit_msg: "chore(pre-commit): auto-fixes from pre-commit hooks"
  skip: []
  submodules: false