name: dch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - pip>=23
  - numpy>=1.24,<2.1
  - scipy>=1.10
  - pandas>=2.0,<3
  - scikit-learn>=1.3,<2
  - networkx>=3.0,<4
  - pyyaml>=6.0
  - statsmodels>=0.14
  - tensorboard>=2.12
  - graphviz
  - pip:
      - torch>=2.2
      - norse>=0.0.9
      - tonic>=1.4.0
      - hydra-core>=1.3
      - tqdm>=4.65
      - rich>=13.0
      - typing_extensions>=4.7